### ISSUE TITLE
[FEAT] 이미지 파일 경로 수정

### ISSUE THREAD

**Issue by Yeyeong99** [swimjiy/sullivan_project_I-dle#18]
## SUMMARY

절대경로로 설정해뒀던 이미지 경로를 상대 경로로 수정합니다.

## CHECKLIST
- [x] week 4
- [x] week 5
- [x] week 6

## ETC

이 외 특이사항을 명시해주세요.

**Comment by swimjiy** [comment]
이슈 안닫힌 것 같아서 닫아놓겠습니다!
